name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"      
    #container:
      # image: node:13.5.0-alpine3.10
      # ports: volumes: options: --cpus 1 --host
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"dwded\" }' "
     # - name: Log node version
      #  run: |
       #   node -v
        #  cat /etc/os-release
      - name: Get users
        run: curl http://localhost:3001/api/users



  
